
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyqcbumwqcatihflqxzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cWNidW13cWNhdGloZmxxeHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Nzc3NTUsImV4cCI6MjA2MDM1Mzc1NX0.igW7iXWWSuBJbwTOgBrPOCMWyaPH_HXFcTqxc24KAnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
